name: Industrialisation continue sur le serveur Alwaysdata
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Flask app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd $HOME/www/
            git clone https://github.com/bstocker/flask_hello_world.git
            rsync -r ./flask_hello_world/ ./flask
            rm -rf ./flask_hello_world
            curl -X POST --basic --user "${{ secrets.ALWAYSDATA_TOKEN }}:" https://api.alwaysdata.com/v1/site/${{ secrets.ALWAYSDATA_SITE_ID }}/restart/
